version: "3.8"
services:
  db:
    build:
      context: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres

  shutter:
    build:
      context: shutter
      args:
        ASSETS_VERSION: shutter-gnosis-1000-set-1v2 # $NETWORK-10*$CHAIN_ID-set-$VERSION
        UPSTREAM_VERSION: gnosis-v1.2.1
        SHUTTER_CONFIG_DIR: /config
        SHUTTER_CHAIN_DATA_DIR: /chain
        STAKER_SCRIPTS_VERSION: v0.1.0
    restart: unless-stopped
    environment:
      SHUTTER_GNOSIS_NODE_PRIVATEKEY: ""
      SHUTTER_METRICS_ENABLED: false
      KEYPER_NAME: ""
    volumes:
      - chain_data:/chain
      - config:/config

volumes:
  db_data: {}
  chain_data: {}
  config: {}
